version: "3"

tasks:
  default:
    cmds:
      - task: dependencies

  docker:
    cmds:
      - task: docker-static
      - task: docker-node

  dependencies:
    cmds:
      - pnpm install

  dev:
    cmds:
      - pnpm dev

  build:
    cmds:
      - pnpm run build

  test:
    cmds:
      - pnpm test

  test-ci:
    cmds:
      - pnpm test:ci

  act-latest:
    cmds:
      - act -W '.github/workflows/docker-latest.yml' --container-architecture linux/amd64

  docker-static:
    cmds:
      - docker buildx build --platform inux/amd64,linux/arm64 . -f ./docker/static/Dockerfile
        -t dev01d/personal-site:static -t dev01d/personal-site:latest --push

  docker-node:
    cmds:
      - docker buildx build --platform linux/amd64,linux/arm64 . -f ./docker/node/Dockerfile -t dev01d/personal-site:node --push

  docker-test:
    cmds:
      - docker build . -f ./docker/node/Dockerfile -t dev01d/personal-site:node
