version: "3"

tasks:
  default:
    cmds:
      - task: dependencies

  dependencies:
    cmds:
      - pnpm install

  dev:
    cmds:
      - pnpm dev

  build:
    cmds:
      - pnpm run build

  test:
    cmds:
      - pnpm test

  test-ci:
    cmds:
      - pnpm test:ci

  static:
    cmds:
      - docker buildx build --platform=linux/amd64,linux/arm64 . -f ./docker/Dockerfile.static
        -t dev01d/personal-site:static -t dev01d/personal-site:latest --push

  node:
    cmds:
      - docker buildx build --platform=linux/amd64,linux/arm64 . -f ./docker/Dockerfile.node -t dev01d/personal-site:node --push
