version: "3"
services:
  caddy-gen:
    image: wemakeservices/caddy-gen:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./caddy-info:/data/caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - site

  site:
    image: dev01d/personal-site:static
    restart: unless-stopped
    labels:
      - "virtual.host=jasonbehnke.io"
      - "virtual.alias=www.jasonbehnke.io"
      - "virtual.port=3000"
      - "virtual.tls-email="
