####* Build ENV ####
FROM node:lts-alpine3.11 as build
WORKDIR /app
COPY package.json package.json
COPY public public
COPY pages pages
COPY src src
COPY yarn.lock yarn.lock
RUN yarn install
RUN yarn build && yarn export

####* Build App ####
FROM nginx:alpine as app
LABEL maintainer="Jason Behnke <contact@jasonbehnke.io>"
COPY ./docker/default.conf /etc/nginx/conf.d/
COPY --from=build /app/out /usr/share/nginx/html/
