name: ci

on:
  push:
    tags:
      - "*"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push static
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.static
          platforms: linux/amd64,linux/arm64
          push: true
          tags: dev01d/personal-site:static
          tags: dev01d/personal-site:${{ github.event.release.tag_name }}-static

      - name: Build and push node
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.node
          platforms: linux/amd64,linux/arm64
          push: true
          tags: dev01d/personal-site:node
          tags: dev01d/personal-site:${{ github.event.release.tag_name }}-node
