name: Docker :Latest release

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  lint-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke lint-and-test
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Lint and test

  docker-release-latest:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.static
          platforms: linux/amd64,linux/arm64
          push: true
          tags: dev01d/personal-site:latest
