name: Docker SemVer release

on:
  push:
    tags:
      - "*"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "17"
          cache: "yarn"

      - name: Install deps
        run: yarn --no-progress --non-interactive --no-lockfile

      - name: Lint code
        run: yarn lint

      - name: Test
        run: yarn test:ci

  docker-release:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta static
        id: meta-static
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=false
          images: |
            dev01d/personal-site
          tags: |
            type=raw,value=static,priority=1
            type=semver,event=tag,pattern={{version}},suffix=-static

      - name: Build and push static
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.static
          platforms: linux/amd64,linux/arm64
          push: true
          labels: ${{ steps.meta-static.outputs.labels }}
          tags: ${{ steps.meta-static.outputs.tags }}

      - name: Docker meta node
        id: meta-node
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=false
          images: |
            dev01d/personal-site
          tags: |
            type=raw,value=node,priority=1
            type=semver,event=tag,pattern={{version}},suffix=-node

      - name: Build and push node
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.node
          platforms: linux/amd64,linux/arm64
          push: true
          labels: ${{ steps.meta-node.outputs.labels }}
          tags: ${{ steps.meta-node.outputs.tags }}
