name: Lint and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "yarn"
      - name: Install
        run: yarn --no-progress --non-interactive --no-lockfile
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test:ci

  call-docker-latest:
    needs: lint-and-test
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/docker-latest.yml
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
