name: Metrics

on:
  schedule:
    - cron: '0 0 * * SUN'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke lint-and-test
        uses: benc-uk/workflow-dispatch@v1.2.3
        with:
          workflow: Lint and test

  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@v4
        with:
          filename: .github/github-metrics.*
          token: NOT_NEEDED
          # Options
          template: classic
          base: ''
          config_timezone: America/Los_Angeles
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: https://jasonbehnke.io
