name: Metrics
on:
  schedule:
    - cron: '0 0 * * SUN'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-and-test-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install deps
        run: pnpm i -s --frozen-lockfile

      - name: Lint code
        run: pnpm lint

      - name: Test
        run: pnpm test:ci

  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          filename: .github/github-metrics.*
          token: NOT_NEEDED
          # Options
          template: classic
          base: ''
          config_timezone: America/Los_Angeles
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: https://jasonbehnke.io
