name: Metrics
on:
  schedule:
    - cron: '0 0 * * SUN'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: lint-and-test

  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          filename: .github/github-metrics.*
          token: NOT_NEEDED
          # Options
          template: classic
          base: ''
          config_timezone: America/Los_Angeles
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: https://jasonbehnke.io
