name: Metrics

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@v3.24
        with:
          filename: .github/github-metrics.*
          token: NOT_NEEDED
          # Options
          template: classic
          base: ''
          config_timezone: America/Los_Angeles
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: https://jasonbehnke.io
